### ISSUE TITLE
Test Run is not finished

### ISSUE THREAD

**Issue by sqandrew** [Mikalai-Kabzar/agent-php-Codeception#5]
@Mikalai-Kabzar , thank you! works almost brilliant!

One thing I can't understand is the following:

when Codeception suite is ended, ReportPortal still shows that run is not finished (https://screencast.com/t/cGnqllsSpmUv)
and Run becomes INTERRUPTED after about 1 day

'die' in _afterSuite didn't help

Thank you for your help in advance,

**Comment by Mikalai-Kabzar** [comment]
Updated. 
Force finish functional was added.
